[Alignment 2.0] Qualifier Ranking+Filter compiler implementation
project-ncl/pnc-common pull request #46
Opened 2023-04-25 12:46 UTC by michalovjan

Dependencies:
requires https://github.com/project-ncl/pnc-api/pull/141

2023-04-27 15:06 UTC, vibe13 requested changes

2023-04-27 15:06 UTC, vibe13 commented on src/main/java/org/jboss/pnc/common/sql/NativeQueryBuilder.java
> +        selects.add((table == null || table.isEmpty() ? "" : table + '.') + field);
I would extract `table + (alias == null || alias.isEmpty() ? "" : " AS " + alias)` into a method as it's commonly used

2023-04-27 15:06 UTC, vibe13 commented on src/main/java/org/jboss/pnc/common/sql/NativeQueryBuilder.java
> +                        + (alias == null || alias.isEmpty() ? "" : " AS " + alias));
I would extract `(alias == null || alias.isEmpty() ? "" : " AS " + alias)` into a method as it's commonly used

2023-04-27 15:06 UTC, vibe13 commented on src/main/java/org/jboss/pnc/common/sql/NativeQueryBuilder.java
> +                        + (onClause == null || onClause.isBlank() ? "" : " ON " + onClause));
I would extract `(onClause == null || onClause.isBlank() ? "" : " ON " + onClause)` into a method as it's commonly used

2023-04-28 16:58 UTC, michalovjan commented
@vibe13 rebase on top of master and addressed your comments

2023-05-02 14:41 UTC, janinko commented on src/main/java/org/jboss/pnc/common/sql/NativeQueryBuilder.java
> +public class NativeQueryBuilder {
String concatenation???

2023-05-05 17:18 UTC, merged